title: G3D - A pure WebGL-compatible 3D render engine, works without DOM API
description: A pure WebGL-compatible 3D render engine, works without DOM API
introduction: G3D is a javascript 3D engine based on WebGL, helping users to create and render 3D scenes easily. Compared with other WebGL 3D engines, G3D is a pure render engine, which means it depends on no DOM APIs but just a canvas(or canvas-like) object. This feature makes it possible that G3D works not only in browser but also in some hybrid environments like GCanvas (Weex or ReactNative).
tryText: Try play with G3D
guideText: Guide